version: "3"
services: 
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    # ports :
    #   - 3000-3001:3000
    environment :
      - PORT=3000
    depends_on : 
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wass
      - MONGO_INITDB_ROOT_PASSWORD=wass1
    volumes :
      - mongo-db:/data/db

  redis:
    image: redis
volumes:
  mongo-db:

# docker-compose up --remove-orphans
#  docker logs backend_node-app_1 -f
# docker-compose up --build --force-recreate --renew-anon-volumes
# docker exec -it mongo sh
# docker volume prune *****remove unused volumes
# redis-cli
# KEYS *
# GET Key

# docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d --scale node-app=2